language: node_js
node_js:
- 7
script:
- node ./internals/scripts/generate-templates-for-linting
- npm run test
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_e8d79c07884c_key -iv $encrypted_e8d79c07884c_iv
  -in gcloud-secret.json.enc -out gcloud-secret.json -d
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  email:
    on_failure: change
after_success: npm run coveralls
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: gae
  project: api-project-296770943829
  keyfile: gcloud-secret.json
  verbosity: debug
  on: master
